import type { Metadata } from "next";
import "./globals.css";
import Navbar from "components/Navbar";
import Footer from "components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <article className="container mx-auto mt-8 px-4">{children}</article>
        <Footer />
      </body>
    </html>
  );
}
